openapi: 3.0.3
info:
  title: User API
  version: 1.0.0
  description: API for managing users

servers:
  - url: http://localhost:5220/v1
    description: Local development server

paths:
  /users:
  
    get:
      summary: Get all users
      description: Returns a list of all registered users.
      operationId: GetAllUsers
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDto"
        "401":
          description: Unauthorized - missing or invalid JWT
        "500":
          description: Server error

    put:
      summary: Update authenticated user
      description: Updates the details of the authenticated user.
      operationId: UpdateUser
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      responses:
        "200":
          description: The updated user's details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
        "400":
          description: Bad request - invalid input
        "401":
          description: Unauthorized - missing or invalid JWT
        "404":
          description: User not found
        "500":
          description: Server error

    delete:
      summary: Delete authenticated user
      description: Deletes the authenticated user's account.
      operationId: DeleteUser
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        "204":
          description: No content - user successfully deleted
        "401":
          description: Unauthorized - missing or invalid JWT
        "404":
          description: User not found
        "500":
          description: Server error

  /users/me:
    get:
      summary: Get authenticated user
      description: Returns the details of the authenticated user.
      operationId: GetUser
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: The authenticated user's details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
        "401":
          description: Unauthorized - missing or invalid JWT
        "404":
          description: User not found
        "500":
          description: Server error

components:
  schemas:
    UserDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"

    UserRequest:
      type: object
      properties:
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
